---
ID: "861d30ac-a6a2-4107-b6ff-030c0e63ff05"
Parent: "ecc8aad9-d8cf-43d2-aab4-24c0c246fff1"
Template: "6aa3d36e-620d-44b4-a904-2b3fa7baccb0"
Path: /sitecore/content/Gymster/Home/Trainers
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230427T104924Z
    - ID: "d5614ffc-6007-4e7c-9258-bb5246cafd9c"
      Hint: Navigation Title
      Value: Trainers
