---
ID: "9e4a0e95-7a2a-4c54-b623-06e7856629da"
Parent: "86f52062-85fc-4dd6-a5a0-207768d78726"
Template: "86f52062-85fc-4dd6-a5a0-207768d78726"
Path: /sitecore/templates/Gymster/Data Templates/Carousel Slide/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230427T091800Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
